usb: gadget: configs: Fix compilation without USB_CONFIGFS_UEVENT
After commit: e45760e46f7bf11545f3b5347cec3744c5e631f2

configfs_composite_setup,
configfs_composite_disconnect are left unused as samsung uses its own composite implementation
Guard them with a condition to avoid compilation error

Fixes:
../drivers/usb/gadget/configfs.c:1799:12: error: unused function 'configfs_composite_setup' [-Werror,-Wunused-function]
static int configfs_composite_setup(struct usb_gadget *gadget,
           ^
../drivers/usb/gadget/configfs.c:1824:13: error: unused function 'configfs_composite_disconnect' [-Werror,-Wunused-function]
static void configfs_composite_disconnect(struct usb_gadget *gadget)
            ^
2 errors generated.

Change-Id: I61d8359b4c3274997194188ba47ebaa6568f5189